version: 1
formatters:
  simple:
    format: '%(asctime)s - %(levelname)s - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
  file_handler:
    class: logging.handlers.WatchedFileHandler
    level: ERROR
    formatter: simple
    filename: ./log/application.log
    encoding: utf8
loggers:
  test:
    level: DEBUG
    handlers: [console,file_handler]
    propagate: no